### ISSUE TITLE
Pure Felix cases

### ISSUE THREAD

**Issue by pun-ky** [neva-dev/felix-search-webconsole-plugin#4]
to be fixed:

- org.osgi.framework.storage / on pure distribution ZIP could be empty
- class loading issue when decompile servlet is being called

```
11:36:36.300 [qtp1456240109-30] WARN org.eclipse.jetty.servlet.ServletHandler - Error for /system/console/search/class-decompile
java.lang.NoClassDefFoundError: Could not initialize class com.strobel.assembler.metadata.MetadataSystem
        at com.strobel.decompiler.Decompiler.decompile(Decompiler.java:34)
        at com.neva.felix.webconsole.plugins.search.core.OsgiExplorer.decompileClass(OsgiExplorer.java:130)
        at com.neva.felix.webconsole.plugins.search.rest.ClassDecompileServlet.doGet(ClassDecompileServlet.java:64)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:618)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
        at org.apache.felix.http.base.internal.handler.ServletHandler.hand
```

**Comment by pun-ky** [comment]
fixed in #5
